const resumes = [

	{
		id: 1,
		fullName: "Алихан Сейдахметов",
		position: "Frontend Developer",
		city: "Astana",
		age: 19,
		salary: 350000,
		experience: "1 год",
		skills: ["HTML", "CSS", "JavaScript", "React"],
		about: "Начинающий frontend-разработчик. Любит создавать аккуратные интерфейсы и изучает React.",
		contacts: {
			email: "alikhan.dev@example.com",
			phone: "+7 701 111 22 33",
		},
	},
	{
		id: 2,
		fullName: "Аружан Нуртаева",
		position: "UI/UX Designer",
		city: "Almaty",
		age: 21,
		salary: 400000,
		experience: "2 года",
		skills: ["Figma", "Prototyping", "Design Systems", "User Research"],
		about: "Дизайнер интерфейсов. Работает с мобильными и веб-приложениями.",
		contacts: {
			email: "aruzhan.ui@example.com",
			phone: "+7 705 222 33 44",
		},
	},
	{
		id: 3,
		fullName: "Данияр Ахметов",
		position: "Backend Developer",
		city: "Karaganda",
		age: 23,
		salary: 500000,
		experience: "3 года",
		skills: ["Node.js", "Express", "PostgreSQL", "Docker"],
		about: "Backend-разработчик. Занимается API, базами данных и серверной логикой.",
		contacts: {
			email: "daniyar.back@example.com",
			phone: "+7 777 333 44 55",
		},
	},
	{
		id: 4,
		fullName: "Мадина Омарова",
		position: "QA Engineer",
		city: "Astana",
		age: 20,
		salary: 300000,
		experience: "1.5 года",
		skills: ["Manual Testing", "Test Cases", "Postman", "Bug Reports"],
		about: "QA-инженер. Проверяет веб-приложения, пишет тест-кейсы и баг-репорты.",
		contacts: {
			email: "madina.qa@example.com",
			phone: "+7 708 444 55 66",
		},
	},
	{
		id: 5,
		fullName: "Ерасыл Касымов",
		position: "React Developer",
		city: "Shymkent",
		age: 22,
		salary: 450000,
		experience: "2 года",
		skills: ["JavaScript", "React", "Redux", "SCSS"],
		about: "React-разработчик. Делает интерактивные компоненты и работает с состоянием.",
		contacts: {
			email: "yerassyl.react@example.com",
			phone: "+7 700 555 66 77",
		},
	},
	{
		id: 6,
		fullName: "Айдар Нургалиев",
		position: "Frontend Developer",
		city: "Ust-Kamenogorsk",
		age: 19,
		salary: 308022,
		experience: "1 год",
		skills: ["Java", "Spring Boot", "Maven"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev6@example.com",
			phone: "+7 706 142 28 76",
		},
	},
	{
		id: 7,
		fullName: "Бекзат Оспанов",
		position: "Backend Developer",
		city: "Atyrau",
		age: 20,
		salary: 317278,
		experience: "1.5 года",
		skills: ["Kotlin", "Android SDK", "Jetpack"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev7@example.com",
			phone: "+7 707 149 31 87",
		},
	},
	{
		id: 8,
		fullName: "Гульнара Садыков",
		position: "Full Stack Developer",
		city: "Kostanay",
		age: 21,
		salary: 326534,
		experience: "2 года",
		skills: ["Flutter", "Dart", "Firebase"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev8@example.com",
			phone: "+7 700 156 34 98",
		},
	},
	{
		id: 9,
		fullName: "Даулет Тлеуов",
		position: "React Developer",
		city: "Semey",
		age: 22,
		salary: 335790,
		experience: "2 года",
		skills: ["Docker", "Kubernetes", "CI/CD"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev9@example.com",
			phone: "+7 701 163 37 19",
		},
	},
	{
		id: 10,
		fullName: "Жанар Утегенов",
		position: "Vue Developer",
		city: "Astana",
		age: 23,
		salary: 345046,
		experience: "3 года",
		skills: ["Selenium", "Cypress", "Jest"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev10@example.com",
			phone: "+7 702 170 40 30",
		},
	},
	{
		id: 11,
		fullName: "Ильяс Хасенов",
		position: "Angular Developer",
		city: "Almaty",
		age: 24,
		salary: 354302,
		experience: "3 года",
		skills: ["TensorFlow", "Python", "Pandas"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev11@example.com",
			phone: "+7 703 177 43 41",
		},
	},
	{
		id: 12,
		fullName: "Камила Шарипов",
		position: "Node.js Developer",
		city: "Karaganda",
		age: 25,
		salary: 363558,
		experience: "4 года",
		skills: ["PHP", "Laravel", "MySQL"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev12@example.com",
			phone: "+7 704 184 46 52",
		},
	},
	{
		id: 13,
		fullName: "Марат Аманов",
		position: "Python Developer",
		city: "Shymkent",
		age: 26,
		salary: 372814,
		experience: "5 лет",
		skills: ["Rust", "Actix", "SQLx"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev13@example.com",
			phone: "+7 705 191 49 63",
		},
	},
	{
		id: 14,
		fullName: "Нурлан Бектасов",
		position: "Java Developer",
		city: "Aktobe",
		age: 27,
		salary: 382070,
		experience: "6 лет",
		skills: ["Unity", "C#", "Shader Graph"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev14@example.com",
			phone: "+7 706 198 52 74",
		},
	},
	{
		id: 15,
		fullName: "Олжас Досов",
		position: "Go Developer",
		city: "Pavlodar",
		age: 28,
		salary: 391326,
		experience: "7 лет",
		skills: ["Ruby", "Rails", "Sidekiq"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev15@example.com",
			phone: "+7 707 205 55 85",
		},
	},
	{
		id: 16,
		fullName: "Перизат Ермеков",
		position: "Kotlin Developer",
		city: "Ust-Kamenogorsk",
		age: 29,
		salary: 400582,
		experience: "8 лет",
		skills: ["Elixir", "Phoenix", "Ecto"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev16@example.com",
			phone: "+7 700 212 58 96",
		},
	},
	{
		id: 17,
		fullName: "Руслан Жаксылыков",
		position: "Swift Developer",
		city: "Atyrau",
		age: 30,
		salary: 409838,
		experience: "1 год",
		skills: ["Burp Suite", "OWASP", "Penetration Testing"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev17@example.com",
			phone: "+7 701 219 61 17",
		},
	},
	{
		id: 18,
		fullName: "Санжар Кенжебаев",
		position: "Android Developer",
		city: "Kostanay",
		age: 31,
		salary: 419094,
		experience: "1.5 года",
		skills: ["HTML", "CSS", "JavaScript", "TypeScript"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev18@example.com",
			phone: "+7 702 226 64 28",
		},
	},
	{
		id: 19,
		fullName: "Тимур Мамытов",
		position: "iOS Developer",
		city: "Semey",
		age: 32,
		salary: 428350,
		experience: "2 года",
		skills: ["Vue.js", "Pinia", "Vite"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev19@example.com",
			phone: "+7 703 233 67 39",
		},
	},
	{
		id: 20,
		fullName: "Улжан Рахимов",
		position: "Flutter Developer",
		city: "Astana",
		age: 33,
		salary: 437606,
		experience: "2 года",
		skills: ["Node.js", "Express", "PostgreSQL"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev20@example.com",
			phone: "+7 704 240 70 50",
		},
	},
	{
		id: 21,
		fullName: "Фариза Султанов",
		position: "React Native Developer",
		city: "Almaty",
		age: 34,
		salary: 446862,
		experience: "3 года",
		skills: ["Java", "Spring Boot", "Maven"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev21@example.com",
			phone: "+7 705 247 73 61",
		},
	},
	{
		id: 22,
		fullName: "Хадиша Токтаров",
		position: "DevOps Engineer",
		city: "Karaganda",
		age: 19,
		salary: 456118,
		experience: "3 года",
		skills: ["Kotlin", "Android SDK", "Jetpack"],
		about: "DevOps-инженер. Настраивает CI/CD, контейнеризацию и мониторинг инфраструктуры.",
		contacts: {
			email: "dev22@example.com",
			phone: "+7 706 254 76 72",
		},
	},
	{
		id: 23,
		fullName: "Шыңғыс Усенов",
		position: "SRE",
		city: "Shymkent",
		age: 20,
		salary: 465374,
		experience: "4 года",
		skills: ["Flutter", "Dart", "Firebase"],
		about: "DevOps-инженер. Настраивает CI/CD, контейнеризацию и мониторинг инфраструктуры.",
		contacts: {
			email: "dev23@example.com",
			phone: "+7 707 261 79 83",
		},
	},
	{
		id: 24,
		fullName: "Эльдар Фазылов",
		position: "Cloud Engineer",
		city: "Aktobe",
		age: 21,
		salary: 474630,
		experience: "5 лет",
		skills: ["Docker", "Kubernetes", "CI/CD"],
		about: "DevOps-инженер. Настраивает CI/CD, контейнеризацию и мониторинг инфраструктуры.",
		contacts: {
			email: "dev24@example.com",
			phone: "+7 700 268 82 94",
		},
	},
	{
		id: 25,
		fullName: "Ясмин Ханов",
		position: "Data Engineer",
		city: "Pavlodar",
		age: 22,
		salary: 483886,
		experience: "6 лет",
		skills: ["Selenium", "Cypress", "Jest"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev25@example.com",
			phone: "+7 701 275 85 15",
		},
	},
	{
		id: 26,
		fullName: "Асель Шакиров",
		position: "ML Engineer",
		city: "Ust-Kamenogorsk",
		age: 23,
		salary: 493142,
		experience: "7 лет",
		skills: ["TensorFlow", "Python", "Pandas"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev26@example.com",
			phone: "+7 702 282 88 26",
		},
	},
	{
		id: 27,
		fullName: "Болат Алиев",
		position: "QA Engineer",
		city: "Atyrau",
		age: 24,
		salary: 502398,
		experience: "8 лет",
		skills: ["PHP", "Laravel", "MySQL"],
		about: "QA-инженер. Тестирует веб и API, составляет тест-кейсы и ведёт баг-репорты.",
		contacts: {
			email: "dev27@example.com",
			phone: "+7 703 289 91 37",
		},
	},
	{
		id: 28,
		fullName: "Гаухар Болатов",
		position: "Automation QA Engineer",
		city: "Kostanay",
		age: 25,
		salary: 511654,
		experience: "1 год",
		skills: ["Rust", "Actix", "SQLx"],
		about: "QA-инженер. Тестирует веб и API, составляет тест-кейсы и ведёт баг-репорты.",
		contacts: {
			email: "dev28@example.com",
			phone: "+7 704 296 94 48",
		},
	},
	{
		id: 29,
		fullName: "Диана Газиев",
		position: "Security Engineer",
		city: "Semey",
		age: 26,
		salary: 520910,
		experience: "1.5 года",
		skills: ["Unity", "C#", "Shader Graph"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev29@example.com",
			phone: "+7 705 303 97 59",
		},
	},
	{
		id: 30,
		fullName: "Ерлан Даулетов",
		position: "Blockchain Developer",
		city: "Astana",
		age: 27,
		salary: 530166,
		experience: "2 года",
		skills: ["Ruby", "Rails", "Sidekiq"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev30@example.com",
			phone: "+7 706 310 10 70",
		},
	},
	{
		id: 31,
		fullName: "Жанибек Есенов",
		position: "PHP Developer",
		city: "Almaty",
		age: 28,
		salary: 539422,
		experience: "2 года",
		skills: ["Elixir", "Phoenix", "Ecto"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev31@example.com",
			phone: "+7 707 317 13 81",
		},
	},
	{
		id: 32,
		fullName: "Куаныш Жанибеков",
		position: "C# Developer",
		city: "Karaganda",
		age: 29,
		salary: 548678,
		experience: "3 года",
		skills: ["Burp Suite", "OWASP", "Penetration Testing"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev32@example.com",
			phone: "+7 700 324 16 92",
		},
	},
	{
		id: 33,
		fullName: "Ляззат Касымов",
		position: ".NET Developer",
		city: "Shymkent",
		age: 30,
		salary: 557934,
		experience: "3 года",
		skills: ["HTML", "CSS", "JavaScript", "TypeScript"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev33@example.com",
			phone: "+7 701 331 19 13",
		},
	},
	{
		id: 34,
		fullName: "Меруерт Мусаев",
		position: "Rust Developer",
		city: "Aktobe",
		age: 31,
		salary: 567190,
		experience: "4 года",
		skills: ["Vue.js", "Pinia", "Vite"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev34@example.com",
			phone: "+7 702 338 22 24",
		},
	},
	{
		id: 35,
		fullName: "Назым Нуртаев",
		position: "Embedded Developer",
		city: "Pavlodar",
		age: 32,
		salary: 576446,
		experience: "5 лет",
		skills: ["Node.js", "Express", "PostgreSQL"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev35@example.com",
			phone: "+7 703 345 25 35",
		},
	},
	{
		id: 36,
		fullName: "Ораз Омаров",
		position: "Game Developer",
		city: "Ust-Kamenogorsk",
		age: 33,
		salary: 585702,
		experience: "6 лет",
		skills: ["Java", "Spring Boot", "Maven"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev36@example.com",
			phone: "+7 704 352 28 46",
		},
	},
	{
		id: 37,
		fullName: "Рауан Сейдахметов",
		position: "Tech Lead",
		city: "Atyrau",
		age: 34,
		salary: 594958,
		experience: "7 лет",
		skills: ["Kotlin", "Android SDK", "Jetpack"],
		about: "Техлид. Координирует команду, проектирует архитектуру и следит за качеством кода.",
		contacts: {
			email: "dev37@example.com",
			phone: "+7 705 359 31 57",
		},
	},
	{
		id: 38,
		fullName: "Серик Турсынов",
		position: "Software Architect",
		city: "Kostanay",
		age: 19,
		salary: 604214,
		experience: "8 лет",
		skills: ["Flutter", "Dart", "Firebase"],
		about: "Техлид. Координирует команду, проектирует архитектуру и следит за качеством кода.",
		contacts: {
			email: "dev38@example.com",
			phone: "+7 706 366 34 68",
		},
	},
	{
		id: 39,
		fullName: "Талгат Абдуллин",
		position: "API Developer",
		city: "Semey",
		age: 20,
		salary: 613470,
		experience: "1 год",
		skills: ["Docker", "Kubernetes", "CI/CD"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev39@example.com",
			phone: "+7 707 373 37 79",
		},
	},
	{
		id: 40,
		fullName: "Улан Байжанов",
		position: "Microservices Developer",
		city: "Astana",
		age: 21,
		salary: 622726,
		experience: "1.5 года",
		skills: ["Selenium", "Cypress", "Jest"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev40@example.com",
			phone: "+7 700 380 40 90",
		},
	},
	{
		id: 41,
		fullName: "Айгуль Жумабеков",
		position: "Database Administrator",
		city: "Almaty",
		age: 22,
		salary: 631982,
		experience: "2 года",
		skills: ["TensorFlow", "Python", "Pandas"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev41@example.com",
			phone: "+7 701 387 43 11",
		},
	},
	{
		id: 42,
		fullName: "Багдат Ибрагимов",
		position: "TypeScript Developer",
		city: "Karaganda",
		age: 23,
		salary: 641238,
		experience: "2 года",
		skills: ["PHP", "Laravel", "MySQL"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev42@example.com",
			phone: "+7 702 394 46 22",
		},
	},
	{
		id: 43,
		fullName: "Галия Калиев",
		position: "Scala Developer",
		city: "Shymkent",
		age: 24,
		salary: 650494,
		experience: "3 года",
		skills: ["Rust", "Actix", "SQLx"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev43@example.com",
			phone: "+7 703 401 49 33",
		},
	},
	{
		id: 44,
		fullName: "Динара Мухамедов",
		position: "Ruby Developer",
		city: "Aktobe",
		age: 25,
		salary: 659750,
		experience: "3 года",
		skills: ["Unity", "C#", "Shader Graph"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev44@example.com",
			phone: "+7 704 408 52 44",
		},
	},
	{
		id: 45,
		fullName: "Еркежан Нургалиев",
		position: "Elixir Developer",
		city: "Pavlodar",
		age: 26,
		salary: 669006,
		experience: "4 года",
		skills: ["Ruby", "Rails", "Sidekiq"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev45@example.com",
			phone: "+7 705 415 55 55",
		},
	},
	{
		id: 46,
		fullName: "Айбек Оспанов",
		position: "GraphQL Developer",
		city: "Ust-Kamenogorsk",
		age: 27,
		salary: 678262,
		experience: "5 лет",
		skills: ["Elixir", "Phoenix", "Ecto"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev46@example.com",
			phone: "+7 706 422 58 66",
		},
	},
	{
		id: 47,
		fullName: "Берик Садыков",
		position: "Platform Engineer",
		city: "Atyrau",
		age: 28,
		salary: 687518,
		experience: "6 лет",
		skills: ["Burp Suite", "OWASP", "Penetration Testing"],
		about: "DevOps-инженер. Настраивает CI/CD, контейнеризацию и мониторинг инфраструктуры.",
		contacts: {
			email: "dev47@example.com",
			phone: "+7 707 429 61 77",
		},
	},
	{
		id: 48,
		fullName: "Гульмира Тлеуов",
		position: "Site Reliability Engineer",
		city: "Kostanay",
		age: 29,
		salary: 696774,
		experience: "7 лет",
		skills: ["HTML", "CSS", "JavaScript", "TypeScript"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev48@example.com",
			phone: "+7 700 436 64 88",
		},
	},
	{
		id: 49,
		fullName: "Дастан Утегенов",
		position: "Mobile Developer",
		city: "Semey",
		age: 30,
		salary: 706030,
		experience: "8 лет",
		skills: ["Vue.js", "Pinia", "Vite"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev49@example.com",
			phone: "+7 701 443 67 99",
		},
	},
	{
		id: 50,
		fullName: "Ербол Хасенов",
		position: "Frontend Developer",
		city: "Astana",
		age: 31,
		salary: 715286,
		experience: "1 год",
		skills: ["Node.js", "Express", "PostgreSQL"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev50@example.com",
			phone: "+7 702 450 70 20",
		},
	},
	{
		id: 51,
		fullName: "Жансая Шарипов",
		position: "Backend Developer",
		city: "Almaty",
		age: 32,
		salary: 724542,
		experience: "1.5 года",
		skills: ["Java", "Spring Boot", "Maven"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev51@example.com",
			phone: "+7 703 457 73 31",
		},
	},
	{
		id: 52,
		fullName: "Канат Аманов",
		position: "Full Stack Developer",
		city: "Karaganda",
		age: 33,
		salary: 733798,
		experience: "2 года",
		skills: ["Kotlin", "Android SDK", "Jetpack"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev52@example.com",
			phone: "+7 704 464 76 42",
		},
	},
	{
		id: 53,
		fullName: "Мейрам Бектасов",
		position: "React Developer",
		city: "Shymkent",
		age: 34,
		salary: 743054,
		experience: "2 года",
		skills: ["Flutter", "Dart", "Firebase"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev53@example.com",
			phone: "+7 705 471 79 53",
		},
	},
	{
		id: 54,
		fullName: "Нурбек Досов",
		position: "Vue Developer",
		city: "Aktobe",
		age: 19,
		salary: 752310,
		experience: "3 года",
		skills: ["Docker", "Kubernetes", "CI/CD"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev54@example.com",
			phone: "+7 706 478 82 64",
		},
	},
	{
		id: 55,
		fullName: "Сабина Ермеков",
		position: "Angular Developer",
		city: "Pavlodar",
		age: 20,
		salary: 761566,
		experience: "3 года",
		skills: ["Selenium", "Cypress", "Jest"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev55@example.com",
			phone: "+7 707 485 85 75",
		},
	},
	{
		id: 56,
		fullName: "Айдар Жаксылыков",
		position: "Node.js Developer",
		city: "Ust-Kamenogorsk",
		age: 21,
		salary: 770822,
		experience: "4 года",
		skills: ["TensorFlow", "Python", "Pandas"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev56@example.com",
			phone: "+7 700 492 88 86",
		},
	},
	{
		id: 57,
		fullName: "Бекзат Кенжебаев",
		position: "Python Developer",
		city: "Atyrau",
		age: 22,
		salary: 780078,
		experience: "5 лет",
		skills: ["PHP", "Laravel", "MySQL"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev57@example.com",
			phone: "+7 701 499 91 97",
		},
	},
	{
		id: 58,
		fullName: "Гульнара Мамытов",
		position: "Java Developer",
		city: "Kostanay",
		age: 23,
		salary: 789334,
		experience: "6 лет",
		skills: ["Rust", "Actix", "SQLx"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev58@example.com",
			phone: "+7 702 506 94 18",
		},
	},
	{
		id: 59,
		fullName: "Даулет Рахимов",
		position: "Go Developer",
		city: "Semey",
		age: 24,
		salary: 798590,
		experience: "7 лет",
		skills: ["Unity", "C#", "Shader Graph"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev59@example.com",
			phone: "+7 703 513 97 29",
		},
	},
	{
		id: 60,
		fullName: "Жанар Султанов",
		position: "Kotlin Developer",
		city: "Astana",
		age: 25,
		salary: 307846,
		experience: "8 лет",
		skills: ["Ruby", "Rails", "Sidekiq"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev60@example.com",
			phone: "+7 704 520 10 40",
		},
	},
	{
		id: 61,
		fullName: "Ильяс Токтаров",
		position: "Swift Developer",
		city: "Almaty",
		age: 26,
		salary: 317102,
		experience: "1 год",
		skills: ["Elixir", "Phoenix", "Ecto"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev61@example.com",
			phone: "+7 705 527 13 51",
		},
	},
	{
		id: 62,
		fullName: "Камила Усенов",
		position: "Android Developer",
		city: "Karaganda",
		age: 27,
		salary: 326358,
		experience: "1.5 года",
		skills: ["Burp Suite", "OWASP", "Penetration Testing"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev62@example.com",
			phone: "+7 706 534 16 62",
		},
	},
	{
		id: 63,
		fullName: "Марат Фазылов",
		position: "iOS Developer",
		city: "Shymkent",
		age: 28,
		salary: 335614,
		experience: "2 года",
		skills: ["HTML", "CSS", "JavaScript", "TypeScript"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev63@example.com",
			phone: "+7 707 541 19 73",
		},
	},
	{
		id: 64,
		fullName: "Нурлан Ханов",
		position: "Flutter Developer",
		city: "Aktobe",
		age: 29,
		salary: 344870,
		experience: "2 года",
		skills: ["Vue.js", "Pinia", "Vite"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev64@example.com",
			phone: "+7 700 548 22 84",
		},
	},
	{
		id: 65,
		fullName: "Олжас Шакиров",
		position: "React Native Developer",
		city: "Pavlodar",
		age: 30,
		salary: 354126,
		experience: "3 года",
		skills: ["Node.js", "Express", "PostgreSQL"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev65@example.com",
			phone: "+7 701 555 25 95",
		},
	},
	{
		id: 66,
		fullName: "Перизат Алиев",
		position: "DevOps Engineer",
		city: "Ust-Kamenogorsk",
		age: 31,
		salary: 363382,
		experience: "3 года",
		skills: ["Java", "Spring Boot", "Maven"],
		about: "DevOps-инженер. Настраивает CI/CD, контейнеризацию и мониторинг инфраструктуры.",
		contacts: {
			email: "dev66@example.com",
			phone: "+7 702 562 28 16",
		},
	},
	{
		id: 67,
		fullName: "Руслан Болатов",
		position: "SRE",
		city: "Atyrau",
		age: 32,
		salary: 372638,
		experience: "4 года",
		skills: ["Kotlin", "Android SDK", "Jetpack"],
		about: "DevOps-инженер. Настраивает CI/CD, контейнеризацию и мониторинг инфраструктуры.",
		contacts: {
			email: "dev67@example.com",
			phone: "+7 703 569 31 27",
		},
	},
	{
		id: 68,
		fullName: "Санжар Газиев",
		position: "Cloud Engineer",
		city: "Kostanay",
		age: 33,
		salary: 381894,
		experience: "5 лет",
		skills: ["Flutter", "Dart", "Firebase"],
		about: "DevOps-инженер. Настраивает CI/CD, контейнеризацию и мониторинг инфраструктуры.",
		contacts: {
			email: "dev68@example.com",
			phone: "+7 704 576 34 38",
		},
	},
	{
		id: 69,
		fullName: "Тимур Даулетов",
		position: "Data Engineer",
		city: "Semey",
		age: 34,
		salary: 391150,
		experience: "6 лет",
		skills: ["Docker", "Kubernetes", "CI/CD"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev69@example.com",
			phone: "+7 705 583 37 49",
		},
	},
	{
		id: 70,
		fullName: "Улжан Есенов",
		position: "ML Engineer",
		city: "Astana",
		age: 19,
		salary: 400406,
		experience: "7 лет",
		skills: ["Selenium", "Cypress", "Jest"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev70@example.com",
			phone: "+7 706 590 40 60",
		},
	},
	{
		id: 71,
		fullName: "Фариза Жанибеков",
		position: "QA Engineer",
		city: "Almaty",
		age: 20,
		salary: 409662,
		experience: "8 лет",
		skills: ["TensorFlow", "Python", "Pandas"],
		about: "QA-инженер. Тестирует веб и API, составляет тест-кейсы и ведёт баг-репорты.",
		contacts: {
			email: "dev71@example.com",
			phone: "+7 707 597 43 71",
		},
	},
	{
		id: 72,
		fullName: "Хадиша Касымов",
		position: "Automation QA Engineer",
		city: "Karaganda",
		age: 21,
		salary: 418918,
		experience: "1 год",
		skills: ["PHP", "Laravel", "MySQL"],
		about: "QA-инженер. Тестирует веб и API, составляет тест-кейсы и ведёт баг-репорты.",
		contacts: {
			email: "dev72@example.com",
			phone: "+7 700 604 46 82",
		},
	},
	{
		id: 73,
		fullName: "Шыңғыс Мусаев",
		position: "Security Engineer",
		city: "Shymkent",
		age: 22,
		salary: 428174,
		experience: "1.5 года",
		skills: ["Rust", "Actix", "SQLx"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev73@example.com",
			phone: "+7 701 611 49 93",
		},
	},
	{
		id: 74,
		fullName: "Эльдар Нуртаев",
		position: "Blockchain Developer",
		city: "Aktobe",
		age: 23,
		salary: 437430,
		experience: "2 года",
		skills: ["Unity", "C#", "Shader Graph"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev74@example.com",
			phone: "+7 702 618 52 14",
		},
	},
	{
		id: 75,
		fullName: "Ясмин Омаров",
		position: "PHP Developer",
		city: "Pavlodar",
		age: 24,
		salary: 446686,
		experience: "2 года",
		skills: ["Ruby", "Rails", "Sidekiq"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev75@example.com",
			phone: "+7 703 625 55 25",
		},
	},
	{
		id: 76,
		fullName: "Асель Сейдахметов",
		position: "C# Developer",
		city: "Ust-Kamenogorsk",
		age: 25,
		salary: 455942,
		experience: "3 года",
		skills: ["Elixir", "Phoenix", "Ecto"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev76@example.com",
			phone: "+7 704 632 58 36",
		},
	},
	{
		id: 77,
		fullName: "Болат Турсынов",
		position: ".NET Developer",
		city: "Atyrau",
		age: 26,
		salary: 465198,
		experience: "3 года",
		skills: ["Burp Suite", "OWASP", "Penetration Testing"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev77@example.com",
			phone: "+7 705 639 61 47",
		},
	},
	{
		id: 78,
		fullName: "Гаухар Абдуллин",
		position: "Rust Developer",
		city: "Kostanay",
		age: 27,
		salary: 474454,
		experience: "4 года",
		skills: ["HTML", "CSS", "JavaScript", "TypeScript"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev78@example.com",
			phone: "+7 706 646 64 58",
		},
	},
	{
		id: 79,
		fullName: "Диана Байжанов",
		position: "Embedded Developer",
		city: "Semey",
		age: 28,
		salary: 483710,
		experience: "5 лет",
		skills: ["Vue.js", "Pinia", "Vite"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev79@example.com",
			phone: "+7 707 653 67 69",
		},
	},
	{
		id: 80,
		fullName: "Ерлан Жумабеков",
		position: "Game Developer",
		city: "Astana",
		age: 29,
		salary: 492966,
		experience: "6 лет",
		skills: ["Node.js", "Express", "PostgreSQL"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev80@example.com",
			phone: "+7 700 660 70 80",
		},
	},
	{
		id: 81,
		fullName: "Жанибек Ибрагимов",
		position: "Tech Lead",
		city: "Almaty",
		age: 30,
		salary: 502222,
		experience: "7 лет",
		skills: ["Java", "Spring Boot", "Maven"],
		about: "Техлид. Координирует команду, проектирует архитектуру и следит за качеством кода.",
		contacts: {
			email: "dev81@example.com",
			phone: "+7 701 667 73 91",
		},
	},
	{
		id: 82,
		fullName: "Куаныш Калиев",
		position: "Software Architect",
		city: "Karaganda",
		age: 31,
		salary: 511478,
		experience: "8 лет",
		skills: ["Kotlin", "Android SDK", "Jetpack"],
		about: "Техлид. Координирует команду, проектирует архитектуру и следит за качеством кода.",
		contacts: {
			email: "dev82@example.com",
			phone: "+7 702 674 76 12",
		},
	},
	{
		id: 83,
		fullName: "Ляззат Мухамедов",
		position: "API Developer",
		city: "Shymkent",
		age: 32,
		salary: 520734,
		experience: "1 год",
		skills: ["Flutter", "Dart", "Firebase"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev83@example.com",
			phone: "+7 703 681 79 23",
		},
	},
	{
		id: 84,
		fullName: "Меруерт Нургалиев",
		position: "Microservices Developer",
		city: "Aktobe",
		age: 33,
		salary: 529990,
		experience: "1.5 года",
		skills: ["Docker", "Kubernetes", "CI/CD"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev84@example.com",
			phone: "+7 704 688 82 34",
		},
	},
	{
		id: 85,
		fullName: "Назым Оспанов",
		position: "Database Administrator",
		city: "Pavlodar",
		age: 34,
		salary: 539246,
		experience: "2 года",
		skills: ["Selenium", "Cypress", "Jest"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev85@example.com",
			phone: "+7 705 695 85 45",
		},
	},
	{
		id: 86,
		fullName: "Ораз Садыков",
		position: "TypeScript Developer",
		city: "Ust-Kamenogorsk",
		age: 19,
		salary: 548502,
		experience: "2 года",
		skills: ["TensorFlow", "Python", "Pandas"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev86@example.com",
			phone: "+7 706 702 88 56",
		},
	},
	{
		id: 87,
		fullName: "Рауан Тлеуов",
		position: "Scala Developer",
		city: "Atyrau",
		age: 20,
		salary: 557758,
		experience: "3 года",
		skills: ["PHP", "Laravel", "MySQL"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev87@example.com",
			phone: "+7 707 709 91 67",
		},
	},
	{
		id: 88,
		fullName: "Серик Утегенов",
		position: "Ruby Developer",
		city: "Kostanay",
		age: 21,
		salary: 567014,
		experience: "3 года",
		skills: ["Rust", "Actix", "SQLx"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev88@example.com",
			phone: "+7 700 716 94 78",
		},
	},
	{
		id: 89,
		fullName: "Талгат Хасенов",
		position: "Elixir Developer",
		city: "Semey",
		age: 22,
		salary: 576270,
		experience: "4 года",
		skills: ["Unity", "C#", "Shader Graph"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev89@example.com",
			phone: "+7 701 723 97 89",
		},
	},
	{
		id: 90,
		fullName: "Улан Шарипов",
		position: "GraphQL Developer",
		city: "Astana",
		age: 23,
		salary: 585526,
		experience: "5 лет",
		skills: ["Ruby", "Rails", "Sidekiq"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev90@example.com",
			phone: "+7 702 730 10 10",
		},
	},
	{
		id: 91,
		fullName: "Айгуль Аманов",
		position: "Platform Engineer",
		city: "Almaty",
		age: 24,
		salary: 594782,
		experience: "6 лет",
		skills: ["Elixir", "Phoenix", "Ecto"],
		about: "DevOps-инженер. Настраивает CI/CD, контейнеризацию и мониторинг инфраструктуры.",
		contacts: {
			email: "dev91@example.com",
			phone: "+7 703 737 13 21",
		},
	},
	{
		id: 92,
		fullName: "Багдат Бектасов",
		position: "Site Reliability Engineer",
		city: "Karaganda",
		age: 25,
		salary: 604038,
		experience: "7 лет",
		skills: ["Burp Suite", "OWASP", "Penetration Testing"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev92@example.com",
			phone: "+7 704 744 16 32",
		},
	},
	{
		id: 93,
		fullName: "Галия Досов",
		position: "Mobile Developer",
		city: "Shymkent",
		age: 26,
		salary: 613294,
		experience: "8 лет",
		skills: ["HTML", "CSS", "JavaScript", "TypeScript"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev93@example.com",
			phone: "+7 705 751 19 43",
		},
	},
	{
		id: 94,
		fullName: "Динара Ермеков",
		position: "Frontend Developer",
		city: "Aktobe",
		age: 27,
		salary: 622550,
		experience: "1 год",
		skills: ["Vue.js", "Pinia", "Vite"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev94@example.com",
			phone: "+7 706 758 22 54",
		},
	},
	{
		id: 95,
		fullName: "Еркежан Жаксылыков",
		position: "Backend Developer",
		city: "Pavlodar",
		age: 28,
		salary: 631806,
		experience: "1.5 года",
		skills: ["Node.js", "Express", "PostgreSQL"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev95@example.com",
			phone: "+7 707 765 25 65",
		},
	},
	{
		id: 96,
		fullName: "Айбек Кенжебаев",
		position: "Full Stack Developer",
		city: "Ust-Kamenogorsk",
		age: 29,
		salary: 641062,
		experience: "2 года",
		skills: ["Java", "Spring Boot", "Maven"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev96@example.com",
			phone: "+7 700 772 28 76",
		},
	},
	{
		id: 97,
		fullName: "Берик Мамытов",
		position: "React Developer",
		city: "Atyrau",
		age: 30,
		salary: 650318,
		experience: "2 года",
		skills: ["Kotlin", "Android SDK", "Jetpack"],
		about: "Любит автоматизировать рутину, покрывать код тестами и работать по agile.",
		contacts: {
			email: "dev97@example.com",
			phone: "+7 701 779 31 87",
		},
	},
	{
		id: 98,
		fullName: "Гульмира Рахимов",
		position: "Vue Developer",
		city: "Kostanay",
		age: 31,
		salary: 659574,
		experience: "3 года",
		skills: ["Flutter", "Dart", "Firebase"],
		about: "Разработчик с опытом в коммерческих проектах. Пишет поддерживаемый код и участвует в code review.",
		contacts: {
			email: "dev98@example.com",
			phone: "+7 702 786 34 98",
		},
	},
	{
		id: 99,
		fullName: "Дастан Султанов",
		position: "Angular Developer",
		city: "Semey",
		age: 32,
		salary: 668830,
		experience: "3 года",
		skills: ["Docker", "Kubernetes", "CI/CD"],
		about: "Специализируется на веб-разработке и оптимизации производительности приложений.",
		contacts: {
			email: "dev99@example.com",
			phone: "+7 703 793 37 19",
		},
	},
	{
		id: 100,
		fullName: "Ербол Токтаров",
		position: "Node.js Developer",
		city: "Astana",
		age: 33,
		salary: 678086,
		experience: "4 года",
		skills: ["Selenium", "Cypress", "Jest"],
		about: "Участвовал в разработке CRM, маркетплейсов и внутренних сервисов компании.",
		contacts: {
			email: "dev100@example.com",
			phone: "+7 704 800 40 30",
		},
	},

]
const fakeFetch = (data, delay = 700) => {
	return new Promise((resolve) => {
		setTimeout(() => {
			resolve(data)
		}, delay)
	})
}

export const getResumes = () => {
	return fakeFetch(resumes).then((data) => {
		return data
	})
}

export const getResumeById = (id) => {
	return fakeFetch(resumes).then((data) => {
		const resume = data.find((resume) => resume.id === Number(id))

		if (!resume) {
			throw new Error("Резюме не найдено")
		}

		return resume
	})
}
